function toDescription(string) {
    const splitted = string.split('\t')
    return `/**` + '\n'
    + ` * ${splitted[2]}` + '\n'
    + ` * \`\`\`` + '\n'
    + `${splitted[3]?.split('\n')?.slice(1)?.map(line => ` * ${line}`)?.join('\n')}` + '\n'
    + ` * \`\`\`` + '\n'
    + ` */` + '\n'
    + `${splitted[0]}: () => void` + '\n'
}

JSON.parse(`["goToFloor\\tfunction\\tQueue the elevator to go to specified floor number. If you specify true as second argument, the elevator will go to that floor directly, and then go to any other queued floors.\\t\\nelevator.goToFloor(3); // Do it after anything else\\nelevator.goToFloor(2, true); // Do it before anything else","stop\\tfunction\\tClear the destination queue and stop the elevator if it is moving. Note that you normally don't need to stop elevators - it is intended for advanced solutions with in-transit rescheduling logic. Also, note that the elevator will probably not stop at a floor, so passengers will not get out.\\t\\nelevator.stop();","currentFloor\\tfunction\\tGets the floor number that the elevator currently is on.\\t\\nif(elevator.currentFloor() === 0) {\\n    // Do something special?\\n}","goingUpIndicator\\tfunction\\tGets or sets the going up indicator, which will affect passenger behaviour when stopping at floors.\\t\\nif(elevator.goingUpIndicator()) {\\n    elevator.goingDownIndicator(false);\\n}","goingDownIndicator\\tfunction\\tGets or sets the going down indicator, which will affect passenger behaviour when stopping at floors.\\t\\nif(elevator.goingDownIndicator()) {\\n    elevator.goingUpIndicator(false);\\n}","maxPassengerCount\\tfunction\\tGets the maximum number of passengers that can occupy the elevator at the same time.\\t\\nif(elevator.maxPassengerCount() > 5) {\\n    // Use this elevator for something special, because it's big\\n}","loadFactor\\tfunction\\tGets the load factor of the elevator. 0 means empty, 1 means full. Varies with passenger weights, which vary - not an exact measure.\\t\\nif(elevator.loadFactor() < 0.4) {\\n    // Maybe use this elevator, since it's not full yet?\\n}","destinationDirection\\tfunction\\tGets the direction the elevator is currently going to move toward. Can be \\"up\\", \\"down\\" or \\"stopped\\".","destinationQueue\\tarray\\tThe current destination queue, meaning the floor numbers the elevator is scheduled to go to. Can be modified and emptied if desired. Note that you need to call checkDestinationQueue() for the change to take effect immediately.\\t\\nelevator.destinationQueue = [];\\nelevator.checkDestinationQueue();","checkDestinationQueue\\tfunction\\tChecks the destination queue for any new destinations to go to. Note that you only need to call this if you modify the destination queue explicitly.\\t\\nelevator.checkDestinationQueue();","getPressedFloors\\tfunction\\tGets the currently pressed floor numbers as an array.\\t\\nif(elevator.getPressedFloors().length > 0) {\\n    // Maybe go to some chosen floor first?\\n}"]`)
    .map(toDescription)
    .forEach((s) => console.log(s))
